### ISSUE TITLE
Sunrise, sunset, moon rise, moon set times are not accurate

### ISSUE THREAD

**Issue by jkandasa** [shred/commons-suncalc#1]
@shred Thank you so much for the great library. 
I see accuracy problem on timings (I do not use other than times).  I test for the date 19-Jan-2017(timezone IST +5:30, Lat/Long: 11°13'N / 78°10'E) and shows bit different value.
```
SunTimes sunTimes = SunTimes.of(new Date(), 11.13, 78.10);
System.out.println(sunTimes.toString());
MoonTimes moonTimes = MoonTimes.of(new Date(), 11.13, 78.10);
System.out.println(moonTimes.toString());
```
Result:
```
SunTimes[sunrise=Thu Jan 19 06:42:29 IST 2017, sunriseEnd=Thu Jan 19 06:44:49 IST 2017, goldenHourEnd=Thu Jan 19 07:12:24 IST 2017, solarNoon=Thu Jan 19 12:29:23 IST 2017, goldenHour=Thu Jan 19 17:46:23 IST 2017, sunsetStart=Thu Jan 19 18:13:58 IST 2017, sunset=Thu Jan 19 18:16:17 IST 2017, dusk=Thu Jan 19 18:38:43 IST 2017, nauticalDusk=Thu Jan 19 19:04:36 IST 2017, night=Thu Jan 19 19:30:22 IST 2017, nadir=Thu Jan 19 00:29:23 IST 2017, nightEnd=Thu Jan 19 05:28:24 IST 2017, nauticalDawn=Thu Jan 19 05:54:10 IST 2017, dawn=Thu Jan 19 06:20:04 IST 2017]
MoonTimes[rise=null, set=Thu Jan 19 11:46:29 IST 2017, alwaysUp=false, alwaysDown=false]
```

The result on Online: https://www.timeanddate.com/astronomy/india/namakkal
I compared with different source all looks very near but your library show more than a minute different,
![image](https://cloud.githubusercontent.com/assets/1004403/22106612/8c8dd1a6-de6f-11e6-9193-dff194d367d7.png)

**Comment by shred** [comment]
Thank you for your report! This library is a Java port of the JavaScript library [mourner/suncalc](https://github.com/mourner/suncalc), and uses the same calculations. I don't have any astronomical background and cannot assess if this implementation is accurate or not. But to quote @mourner:

> These kinds of libraries simply can't be accurate up to the seconds. They each do certain simplifications to make the calculation simpler, and don't account for some things like altitude or weather conditions.

It seems that suncalc [might get a rewrite](https://github.com/mourner/suncalc/issues/57) that is more precise. If it is available, I will adapt this Java port to the new code.

Until then, however, I'm afraid we'll have to live with the time differences, so I will close this bug.

**Comment by jkandasa** [comment]
@shred Thank you :)
