### ISSUE TITLE
Rename library to AstroCalc

### ISSUE THREAD

**Issue by jalil1408** [shred/commons-suncalc#10]
I suggest to rename the library to **AstroCalc** because it calculates more than sun details, it calculates moon details and other **planets** in the future I hope ;)

**Comment by shred** [comment]
You are right, suncalc isn't an accurate name, as the library also computes moon details.

The name has historical reasons. Originally, commons-suncalc v1 was just a Java port of the [suncalc JavaScript library](https://github.com/mourner/suncalc) by @mourner. Although I rewrote it from scratch for v2, I decided to keep the name.

The name is established now, and I actually don't see a real advantage of changing it. Users of this library would need to change their dependency, or they would keep stuck with an old version if they don't change it for whatever reason. Names are but sound and smoke. :wink:

I also have to disappoint you about other planets. commons-suncalc uses a simplified set of formulas for the calculation of sun and moon positions. These formulas only take little CPU power and are sufficiently accurate for "end user" calculations (e.g. for watches or for light switches), but they are insufficient for astronomical purposes. For other planets, a different and a lot more complex set of formulas must be used.

My goal for commons-suncalc is to keep things simple. Making it a full-blown astronomical calculation library, would exceed my time and my rather basic astronomical skills by far. However it is open source, so feel free fork it.
