### ISSUE TITLE
Sunset is always before sunrise for a specific data

### ISSUE THREAD

**Issue by zerdoun** [shred/commons-suncalc#12]

**Comment by zerdoun** [comment]
Hi,
Thanks for the library ! 
I was trying to get the sunset and the sunrise by the current date for example on Mexico City.
But the sunset is always before sunrise.

This is my code:
`Calendar date = Calendar.getInstance();
SunTimes times = SunTimes.compute()
           .on(date)
           .midnight()
           .at(19.3,-99.3)   // set a location
           .execute();     // get the results
System.out.println("Sunrise: " + times.getRise());
System.out.println("Sunset: " + times.getSet());`

And this is my result: 
`Sunrise: Tue Jun 11 11:59:00 GMT 2019
Sunset: Tue Jun 11 01:15:00 GMT 2019`

Thanks a lot for your help :)

**Comment by shred** [comment]
The result is correct. :smile:

Your system uses GMT time zone. What your code is actually asking is: "I'm at a GMT place and it's midnight now. When I'm looking at Mexico City from here (say by a web cam), when is the next sunrise and sunset there?" From that perspective, the sun actually sets first (at 01:15 GMT) and then rises again (at 11:59 GMT).

You need to give the `TimeZone` of the viewer's position:

```java
TimeZone tz = TimeZone.getTimeZone("Mexico/General");

Calendar date = Calendar.getInstance();
SunTimes times = SunTimes.compute()
        .on(date)
        .timezone(tz)
        .midnight()
        .at(19.3,-99.3)
        .execute();

DateFormat fmt = DateFormat.getDateTimeInstance();
fmt.setTimeZone(tz);

System.out.println("Sunrise: " + fmt.format(times.getRise()));
System.out.println("Sunset: " + fmt.format(times.getSet()));
```

Result:

```
Sunrise: 11.06.2019 06:59:00
Sunset: 11.06.2019 20:15:00
```

**Comment by zerdoun** [comment]
Thanks a lot @shred !!!
After your explanation, it's obvious. I forgot Timezone parameter ! 
It works perfectly !!

Thanks for your help again :)

**Comment by shred** [comment]
You're welcome! :smile:
