### ISSUE TITLE
Copyright notice commons-suncalc

### ISSUE THREAD

**Issue by flobetz** [shred/commons-suncalc#16]
Hey Shred,
we are using your commons-suncalc library within our Android App and we have to list your library within our FOSS components. Therefore we need a Copyright notice which is, unfortunately, not available in this repo.
Can you please provide this oneliner?
Greetings
Flo

**Comment by shred** [comment]
I'm not sure what you need exactly. The license itself can be found in the `LICENSE-APL.txt` file. Is it just a one-liner like this?

[commons-suncalc](https://github.com/shred/commons-suncalc) is (c) Richard Körber and distributed under the terms of Apache License 2.0.

**Comment by flobetz** [comment]
That is enough for me, thank you very much 👍
