### ISSUE TITLE
Sun/Moon altitude between 0-180

### ISSUE THREAD

**Issue by rudrab** [shred/commons-suncalc#17]
Hi,
I am trying to fetch sun and moon's altitude (angle from horizon) in this way:
```
      LatLng locknown = new LatLng(latlang.Lat, latlang.Lang);
      Log.e("Hello2", "Res" + latlang.Lang + latlang.Lang);
      SunPosition sunpos = SunPosition.compute()
          .at(locknown.latitude, locknown.longitude)
          .now().execute();
      MoonPosition moonpos = MoonPosition.compute()
          .at(locknown.latitude, locknown.longitude)
          .now().execute();
 googleMap.addMarker(new MarkerOptions().position(locknown)
          .anchor(0.0f, .5f).rotation((Math.abs((float) sunpos.getAltitude())))
          .icon(BitmapDescriptorFactory.fromResource(R.drawable.sun))
          .zIndex(0)
      );
      googleMap.addMarker(new MarkerOptions().position(locknown)
              .anchor(0.0f, .5f).rotation((Math.abs((float) moonpos.getAltitude())))
              .icon(BitmapDescriptorFactory.fromResource(R.drawable.moon))
              .zIndex(0)
      );
```

While this gives some sense that `Altitude` is angle from horizon, unfortunately I cant distinguish between sunrise and sunset, eg the angle is always 0-90, while for me I would like to have it 0-180.

Any idea how I can do that?

**Comment by shred** [comment]
The position is calculated statically for the given time. This means that suncalc doesn't know either whether the sun is rising or falling. It just sees the position at the very moment.

However, you can make use of the fact that the sun and moon are "travelling from east to west". `getAzimuth()` should give you a good hint about if it's sunrise or sunset.
