### ISSUE TITLE
SunTimes noon and nadir are null for .on(Date) near them

### ISSUE THREAD

**Issue by isomeme** [shred/commons-suncalc#18]
When using SunTimes to do calculations starting at an arbitrary point in time using on(Date) -- e.g., to get events for the next 24 hours from now -- the noon value is null if the provided Date is too close to noon, and similarly for nadir. [This test](https://github.com/isomeme/Helios/blob/master/helios/src/test/java/org/onereed/helios/sun/SunCalcTest.java) from my project demonstrates the misbehavior.

**Comment by shred** [comment]
Thank you for the report, and for providing tests! I will have a look into it.

**Comment by shred** [comment]
The reason for the issue was that at the first and last hour of the interval, the curve was badly interpolated. I have extended the interval internally now, to get better results. With that change, your tests ran successfully.

I took the liberty to add your tests to the suncalc test suite. I had to adapt them a bit because I cannot use the new Java time API yet, for maximum Android compatibility.

This bug will be fixed in the coming release v2.7.

Thanks again for the report!

**Comment by shred** [comment]
v2.7 is published and will be available at Maven Central in the next hours.

**Comment by isomeme** [comment]
Wonderful! Thanks very much for the rapid fix. I'll pick up the new version when it's available, and remove some ugly workarounds from my own code. :)

**Comment by Cliff2310** [comment]
FYI
You may have fixed this but I also see the problem at midnight.
	times = SunTimes.compute()
            .on(time[0])    // set a date
            .at(lat, lng)   // set a location
            .execute();     // get the results
	// get day is day of the week?!!!
	System.out.println(db._file_()+" <"+0+"> "+time[0]+" /"+times.getRise());
**<0> Tue Jan 01 00:00:00 CST 2019 /null** 
Cliff

**Comment by Cliff2310** [comment]
Hi just checked and I am using "commons-suncalc-2.7.jar".
Note: times.getSet() works;
Cliff

**Comment by shred** [comment]
Cliff, can you give me the location of your test? If it is above the Arctic Circle, it would be correct that the sun does not rise on January 1st.

**Comment by Cliff2310** [comment]
static double latitude  =   29.554532;  // geolocation 
	    static double longitude =  -95.219382;  // Pearland, TX

**Comment by shred** [comment]
Thank you... I've made a test using your data:

```
        SunTimes times = SunTimes.compute()
                .on(2019, 1, 1)             // set a date
                .at(29.554532, -95.219382)  // set a location
                .execute();                 // get the results
        System.out.println(times.getRise());
```

But the result is `Tue Jan 01 07:16:00 CST 2019`, which is correct.

Can you open a new issue and give me a minimal test that is failing for you?
