### ISSUE TITLE
Any plans for milky way?

### ISSUE THREAD

**Issue by AAverin** [shred/commons-suncalc#2]
Any plans for milky way?

**Comment by shred** [comment]
Sorry... No plans, unless it would be implemented in the JavaScript SunCalc library before.

**Comment by AAverin** [comment]
What about this library?
https://github.com/Fabiz/MeeusJs
It can have some insights

**Comment by shred** [comment]
MeeusJs is an interesting library! But it requires more astronomical knowledge from the user than SunCalc. And I'm afraid it also needs more astronomical knowledge than I have myself. :wink:
