### ISSUE TITLE
After the sunset, the suntimes.getRise() & getSet() methods give the values of the next date.

### ISSUE THREAD

**Issue by tarun-nain** [shred/commons-suncalc#24]
I was getting the sunset and sunrise time from the library and have to change the color of overlay for day and night time. For the comparison, I was using ZonedTime.now() to get the current time and compare whether it is after the sunset. But when the day reaches its end(after sunset time), the getSet() and getRise() starts giving the time for the next date instead of the same date.

**Comment by shred** [comment]
The selected time for the calculation is the start of the time window. This is, if you select a time after sunset, suncalc will give the next sunrise and sunset times, which are (usually) those of the next day.

This example is using the current date and time. If it is past sunrise, `getRise()` will give the sunrise of the next day. If it is past sunset, both `getRise()` and `getSet()` will give the times of the next day.

```
SunTimes times = SunTimes.compute()
    .now()        // current date and time
    .at(somewhere)
    .execute();
System.out.println(times.getRise());
System.out.println(times.getSet());
```

You can add `.midnight()` as a parameter, to make sure that the time window starts at midnight of the current day. You can also add `.oneDay()` to make sure that the result is limited to the next 24 hours.

```
SunTimes times = SunTimes.compute()
    .now()        // current date and time
    .midnight()   // starting at midnight of the current day
    .oneDay()     // limit to the next 24 hours
    .at(somewhere)
    .execute();
System.out.println(times.getRise());
System.out.println(times.getSet());
```

`getRise()` and `getSet()` will now always give the sunrise and sunset times of the current day. (If the sun won't rise or set that day, `null` is returned by the respective getter.)

Could I resolve your issue? If not, please give a code example.

**Comment by tarun-nain** [comment]
Thanks a lot for your quick and detailed response, Shred. Adding .midnight() & .oneDay() to the builder gave the desired output. Now same-day sunrise and sunset are returned. Please close it.
