### ISSUE TITLE
Package without Java.time

### ISSUE THREAD

**Issue by hmulhim** [shred/commons-suncalc#25]
I was using Codenameone and discovered that java.time is not included unfortunately, while your package depends on it, 
How difficuilt it is to convert the suncalc package to use the old time date java system ?

thank you

Aljary!

**Comment by shred** [comment]
You can use [suncalc v2](https://github.com/shred/commons-suncalc/tree/v2). It uses the old Date API, and is still actively maintained.

**Comment by hmulhim** [comment]
Thank you!!
