### ISSUE TITLE
NoClassDefFoundError when using MoonIllumination

### ISSUE THREAD

**Issue by PingPongLee** [shred/commons-suncalc#26]
I get the following exception:

`    java.lang.NoClassDefFoundError: java.util.Objects
        at org.shredzone.commons.suncalc.util.BaseBuilder.timezone(BaseBuilder.java:93)
        at org.shredzone.commons.suncalc.util.BaseBuilder.timezone(BaseBuilder.java:99)
        at com.example.myapplication.MainActivity.onCreate(MainActivity.java:31)`

When I try to use the MoonIllumination class. I've verified the error on a new Android app that targets sdk 16. 

`package com.example.myapplication;

import androidx.appcompat.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.TextView;
import org.shredzone.commons.suncalc.MoonIllumination;
import java.util.Date;

public class MainActivity extends AppCompatActivity {

    @Override
        protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        TextView txt = this.findViewById(R.id.txt);

        Calendar today = Calendar.getInstance();
        int year = today.get(Calendar.YEAR);
        int month = today.get(Calendar.MONTH)+1;
        int day = today.get(Calendar.DAY_OF_MONTH);

        TextView txtDate = this.findViewById(R.id.date);
        txtDate.setText(year + "/" + month + "/" + day);

        try {
            MoonIllumination moon = MoonIllumination.compute()
                    .on(year, month, day)
                    .timezone("Europe/Copenhagen") // <- This is my line 31
                    .execute();
            double phase = moon.getPhase();
            double percent = moon.getFraction() * 100;
            String moonphase = (int)Math.round(percent) + "%";
            txt.setText(moonphase);
        } catch(Exception ex) { }
    }
}`

On the line where it fails I've also tried passing `TimeZone.getDefault()`, but results in the same behavior. Also tried not using `timezone` but the fraction I get is off by 10% 

EDIT: Don't mind the last sentence with the fraction being off. I simply needed to pass, hour, minute and second to the on method too and now its correct. However I would still like to know if the exception mentioned is how its supposed to be. Doing it like this `.on(new Date())` makes the same exception happen

**Comment by shred** [comment]
What suncalc version do you use? The current suncalc v3 requires Android API level 26 or higher. For older Android versions you need to use suncalc v2.

**Comment by PingPongLee** [comment]
I believe I'm using v2.. My gradle looks like so:

`implementation 'org.shredzone.commons:commons-suncalc:2.0'`

Also notice my EDIT in the OP

**Comment by shred** [comment]
Please try version v2.10.

There was a bug regarding older Android versions in all suncalc releases before v2.4. 🙂

**Comment by PingPongLee** [comment]
That did the trick! Working now
