### ISSUE TITLE
Add Dawn and Dusk times

### ISSUE THREAD

**Issue by FJBDev** [shred/commons-suncalc#31]
I would like to get the Dawn and Dusk times in order to differentiate with sun rise/set times.

**Comment by shred** [comment]
There are different twilights (civil, nautical and astronomical) supported by suncalc. You just need to set the desired twilight using the `.twilight()` setter, and then you will get the corresponding dawn and dusk times by invoking `.getRise()` and `.getSet()`.

Also see:
* https://shredzone.org/maven/commons-suncalc/usage.html#twilight
* https://shredzone.org/maven/commons-suncalc/examples.html#twilight

Does it resolve your issue?

**Comment by FJBDev** [comment]
Yes, that definitely resolves my issue, I had not seen that in the documentation.

I am closing this issue.

Thanks!
