### ISSUE TITLE
[Question] Is there some way to get latitude and longitude in Java?

### ISSUE THREAD

**Issue by sblantipodi** [shred/commons-suncalc#32]
Hi,
I want to use the sunrise/sunset feature of this library but I don't know how to get the latitude and longitude from Java.

Is there some suggestion on how to do it?

Thank you!

**Comment by Hamza417** [comment]
There are only two ways to do that, and it is not specific to Java only.

- You can use location provider APIs available in the respective environment, such as in Android you can use [LocationManager](https://developer.android.com/reference/android/location/LocationManager) API
- You can use manual or randomized input for the [LatLng ](https://developers.google.com/android/reference/com/google/android/gms/maps/model/LatLng) or ask the user to do that.

**Comment by isomeme** [comment]
If you are trying to do this in Android, you may benefit from the example of using Android location services and SunCalc together in my project [Helios](https://github.com/isomeme/Helios). [This class](https://github.com/isomeme/Helios/blob/master/helios/src/main/java/org/onereed/helios/location/LocationManager.java) is where most of the interesting location-related stuff happens. The app itself is intended for use with a ritual practice you almost certainly don't care about, but its key purpose is to determine the times of sunrise, noon, sunset, and midnight at the user's location.

**Comment by sblantipodi** [comment]
I am trying to do it in Windows/Linux, not Android.

Thank you!


Il 05/09/2021 20:13, Hamza Rizwan ha scritto:

**Comment by shred** [comment]
Java itself does not provide a geolocation API. This is why suncalc is just using `double` for latitude, longitude, and height.

What you need is some kind of GPS hardware connected to your system. Most GPS receivers use the NMEA 0183 protocol, so you can use something like [Java Marine API](https://github.com/ktuukkan/marine-api) for parsing the NMEA sentences from your GPS device. Depending on how the GPS hardware is connected (e.g. serial port, USB), you might also need a library for the hardware communication. I have never tried that, so I cannot provide more help.

**Comment by sblantipodi** [comment]
ok thank you guys!
