### ISSUE TITLE
How to get the Moonphase for a Date

### ISSUE THREAD

**Issue by binu8051** [shred/commons-suncalc#34]
Hi, while check the code i found that i can get the date of a full moon, new moon and others.
How to get the moonphase with the date, for ex today (25-04-2022)

i am using this code which i got it from other page.

`private int getPhase(Calendar cal) {
        double MOON_PHASE_LENGTH = 29.530588853;
        int year = cal.get(Calendar.YEAR);
        int month = cal.get(Calendar.MONTH) + 1;
        int day = cal.get(Calendar.DAY_OF_MONTH);

        // Convert the year into the format expected by the algorithm.
        double transformedYear = year - Math.floor((12 - month) / 10);

        // Convert the month into the format expected by the algorithm.
        int transformedMonth = month + 9;
        if (transformedMonth >= 12) {
            transformedMonth = transformedMonth - 12;
        }

        // Logic to compute moon phase as a fraction between 0 and 1
        double term1 = Math.floor(365.25 * (transformedYear + 4712));
        double term2 = Math.floor(30.6 * transformedMonth + 0.5);
        double term3 = Math.floor(Math.floor((transformedYear / 100) + 49) * 0.75) - 38;

        double intermediate = term1 + term2 + day + 59;
        if (intermediate > 2299160) {
            intermediate = intermediate - term3;
        }

        double normalizedPhase = (intermediate - 2451550.1) / MOON_PHASE_LENGTH;
        normalizedPhase = normalizedPhase - Math.floor(normalizedPhase);
        if (normalizedPhase < 0) {
            normalizedPhase = normalizedPhase + 1;
        }

        // Return the result as a value between 0 and MOON_PHASE_LENGTH
        double phase = normalizedPhase * MOON_PHASE_LENGTH;

        return ((int) Math.floor(phase)) % 30;
    }`

After getting the moonphase i get the moon state from this code

```
String getMoonPhaseText(int phaseValue) {
        if (phaseValue == 0) {
            return "New";
        } else if (phaseValue > 0 && phaseValue < 7) {
            return "Waxing Crescent";
        } else if (phaseValue == 7) {
            return "First Quarter";
        } else if (phaseValue > 7 && phaseValue < 15) {
            return "Waxing Gibbous";
        } else if (phaseValue == 15) {
            return "Full Moon";
        } else if (phaseValue > 15 && phaseValue < 23) {
            return "Waning Gibbous";
        } else if (phaseValue == 23) {
            return "Third Quarter";
        } else {
            return "Waning Crescent";
        }
    }
```

This code returns the moonphase Length in number 0 to 29, but i found a lot of error in the moonphase output.
I am already using your library for sunrise/set and moonrise/set which are very correct
How to use your library to replace the above code. 
Thanks

**Comment by shred** [comment]
You mean the duration between the current phase and the next time the moon is in that phase?

You can get the phase of a given `date` via `double phase = MoonIllumination.compute().on(date).execute().getPhase()`.

Using `MoonPhase.compute().phase(phase).on(date).plusDays(1).execute().getTime()`, you will get the next date the moon is in that phase.

Now subtract the result from `date` to get the duration of the current moon phase.

**Comment by shred** [comment]
Closing. Feel free to reopen if you need further assistance.
