### ISSUE TITLE
Empty rise and set

### ISSUE THREAD

**Issue by AmirAlkelai** [shred/commons-suncalc#36]
Great work Richard! :)

(using version 2.11) 
I'm having an issue that when I try to get the sunrise time of tomorrow (during sunrise of today). rise is equals null.
Same is happening for sunset.
This happens sometimes only (maybe 25% of the times).
Note that the location is not where there is no sunrise / sunset. This is the location (32.1766423,34.87022270000001)

This is my code:

```
public Calendar getSunriseTime(final Calendar calendar) throws InvalidObjectException {
	final SunTimes times = SunTimes.compute()
            .on(calendar)
            .at(latitude, longitude)
            .execute();
	final Calendar sunCalendar = Calendar.getInstance();
	if (times == null || times.getRise() == null) {
		throw new InvalidObjectException("Sunrise time cannot be calculated"); // The code entered here.
	}
	sunCalendar.setTime(times.getRise());
	return sunCalendar;
}
```

The provided calendar is:
```
Calendar calendar = Calendar.getInstance();
calendar.setFirstDayOfWeek(Calendar.SUNDAY);
calendar.set(Calendar.SECOND, 0);
calendar.set(Calendar.MILLISECOND, 0);
calendar.add(Calendar.DATE, 1);
```

Any idea what can it be?

**Comment by AmirAlkelai** [comment]
I found the issue, since the sunset the next day is happening more than 24h later, I had to set the fullcycle() parameter.

**Comment by shred** [comment]
Yes, that's right. In version 2 of the library, only 24 hours are checked by default. If the sun rises/sets past 24 hours, the result will be `null`.

This was often a source of confusion, so the behavior was changed in version 3, where `fullcycle()` is the default.
