### ISSUE TITLE
how to use the parameters

### ISSUE THREAD

**Issue by rudrab** [shred/commons-suncalc#4]
Hi, How to use the SunTimes parameter to get the twilight, golden hour etc?
I was trying (the latest):
`    SunTimes twilight = SunTimes.Twilight.valueOf("ASTRONOMICAL").compute().at(latlang.Lat, latlang.Lat).today().execute();
`

**Comment by shred** [comment]
Hi rudrab! I'm sorry, the twilight parameter is indeed poorly documented. I'm going to fix that.

You can use a different twilight setting like this:

```java
SunTimes times = SunTimes.compute()
    .twilight(SunTimes.Twilight.ASTRONOMICAL)
    // set your other parameters
    .execute();
```

**Comment by rudrab** [comment]
Hi shred, Thanks a lot.
