### ISSUE TITLE
Feature Request: Basic command line wrapper for the app?

### ISSUE THREAD

**Issue by lexterror** [shred/commons-suncalc#40]
I guess it would be pretty easy to create a cli wrapper for your app.

like: 

Choose one of the following.
[1]sunrise/sunset
[2]moonrise/moonset
[3]etc...

And have follow up questions and wait for input from the user?

I could have that done in a day or two, but I would have to set up the right tools and do a little bit of research before getting started....

**Comment by shred** [comment]
Thank you for the feature proposal.

The basic CLI wrapper might be written in a day or two, but remember that there is also stuff like unit testing, documentation, and future maintenance work (e.g. bug fixing or updating the wrapper for new features). To be honest, I don't really see the benefit to the project, compared to the "costs".

You could write that CLI wrapper in a project of your own, and use suncalc as dependency. When you have completed the project, I will gladly add a link to it in the documentation.

**Comment by lexterror** [comment]
ok thanks!
