### ISSUE TITLE
Anyway to calculate the Tide for a location?

### ISSUE THREAD

**Issue by binu8051** [shred/commons-suncalc#42]
Hi
Can this library predict the Tide for a location.
Binu

**Comment by shred** [comment]
Hi Binu!

It's true that the tide depends on the position of the sun and the moon, so it would be obvious to calculate it with suncalc.

But the tide at a location also depends on sea currents and geological conditions. This library could only give a very rough estimate. At best it might be entertaining, but would have no practical use. At worst, it would be life-threatening if someone relied on the results. For this reason, I deliberately decided NOT to add tide calculation.

There are sophisticated tools for that purpose, for example [JTides](https://arachnoid.com/JTides/).
