### ISSUE TITLE
Sunset Time now returns null

### ISSUE THREAD

**Issue by yitzih** [shred/commons-suncalc#6]
I have started getting a sunset (and sunrise) time of null. This seems to be caused by it being past some date. When subtracting a day from the calendar it works properly, but adding days to the calendar does not seem to make it work again.

This is the code I am using:

```
Calendar today = Calendar.getInstance(TimeZone.getDefault()); //EST Time for testing
today.set(Calendar.HOUR_OF_DAY, 1); //set to beginning of day because SunTimes computes the next sunset
SunTimes sunTimes = SunTimes.compute().on(today.getTime()).at(latitude, longitude).execute();
Date sunsetTime = sunTimes.getSet();
```

**Comment by shred** [comment]
The beginning of the day would be `today.set(Calendar.HOUR_OF_DAY, 0)`. I don't think this will solve your problem, but it's worth a try.

Suncalc does all that date calculation for you, too:

```java
SunTimes sunTimes = SunTimes.compute().today().at(latitude, longitude).execute();
```

`today()` sets last midnight of the current day. Your system's timezone is also used by default.

If you add `fullCycle()` to the chain of parameters, Suncalc will find the next sunrise and sunset, even if on a different date.

If this all does not help or does not give the expected results, please give me the latitude and longitude you were using. It's sufficient to round them to one decimal.

**Comment by yitzih** [comment]
This appeared to be an issue with the Android Emulator. Clearing the device data and cold starting the emulated device fixed the issue.
