### ISSUE TITLE
sun(moon)Position help

### ISSUE THREAD

**Issue by rudrab** [shred/commons-suncalc#7]
Dear shred,
I am using your excellent work for an app. I am stuck in one point with sunPosition. The problem is it shows the getAltitude() in 0-180, i.e. for daytimes only. That obviously makes some sense, but for my purpose, I also need the sun's altitude at night, i.e. 0-360. 

Is it possible to achieve?

**Comment by shred** [comment]
Not quite...

`getAltitude()` takes the atmospheric refraction into account. The refraction formula is only valid for positive altitudes. For this reason, negatives altitudes are returned as 0°.

I could add a method that returns the true altitude of the sun (this is, without refraction). This would give negative altitudes at night. But at daytime, the true sun altitude would seem to be lower than the visible altitude.

Would this help you?

**Comment by rudrab** [comment]
dear shred,
thanks a lot for your reply. 
Yes, your proposal will be helpful, but, let me clear one thing. I am calculating the sun and moon altitude as:
       ```
SunPosition sunangle = SunPosition.compute().at(latlang.Lat,latlang.Lang).now().execute();
        MoonPosition moonangle =MoonPosition.compute().at(latlang.Lat,latlang.Lang).now().execute();
        float sunaltitude =(float)sunangle.getAltitude();
        float moonaltitude = (float) moonangle.getAltitude();
```
 and, it actually does not give 0 after sunset, rather starts to go from 90->-90

I am not sure if I am doing this correctly.

**Comment by shred** [comment]
I'm sorry, it was confusing what I wrote before. The refraction offset is added to the sun's altitude, and that addition is 0° when the sun goes below 0°.

However the altitude is always in the range of -90° to 90°. And it always refers to the visible altitude of the sun. In winter, when the sun is always low, the altitude will never reach 90°, or a value close to that. In polar winters, the angle will even be negative all day.

Suncalc does not provide the angle you are looking for. But you can calculate it yourself, for example if you calculate the nadir of the current and next day (using `SunTimes.getNadir()`), and use cross-multiplication to compute your angle. 0°=nadir of current day, 180°=exact time between both nadirs, 360°=nadir of next day.

**Comment by shred** [comment]
Closing because it's not really a bug in suncalc.
